### ISSUE TITLE
Card creation fails when word isn't in Tatoeba database

### ISSUE THREAD

**Issue by kdelwat** [pcboy/pixmory#3]
Running the following command fails:

```
bundle exec ruby pixmory.rb --wordfile frenchvocab.txt --deckname deck.french --from-lang eng --to-lang fre --no-pronunciation 
```

The error is as follows:

```
/home/cadel/pixmory/core/sentence.rb:69:in `block in sample_sentences': undefined method `length' for nil:NilClass (NoMethodError)
    from /home/cadel/pixmory/core/sentence.rb:69:in `each'
    from /home/cadel/pixmory/core/sentence.rb:69:in `sort_by'
    from /home/cadel/pixmory/core/sentence.rb:69:in `sample_sentences'
    from /home/cadel/pixmory/core/sentence.rb:46:in `save'
    from /home/cadel/pixmory/core/card.rb:14:in `block in save'
    from /home/cadel/pixmory/core/card.rb:13:in `map'
    from /home/cadel/pixmory/core/card.rb:13:in `save'
    from /home/cadel/pixmory/core/deck_builder.rb:16:in `block (2 levels) in save'
    from /home/cadel/pixmory/core/deck_builder.rb:15:in `map'
    from /home/cadel/pixmory/core/deck_builder.rb:15:in `block in save'
    from /home/cadel/pixmory/core/deck_builder.rb:14:in `open'
    from /home/cadel/pixmory/core/deck_builder.rb:14:in `save'
    from pixmory.rb:55:in `start'
    from pixmory.rb:117:in `<main>'
```

Experimentation seems to suggest that the program is failing on the vocab line "the mosque,la mosquée". This is the only word in the vocab file that does not appear in the Tatoeba database.

**Comment by kdelwat** [comment]
On second thoughts, the problem may not be that the word is missing from the Tatoeba database. I just had the same error message with "monday,lundi", both of which appear many times in the sentence list.

**Comment by pcboy** [comment]
Looks like there is some issues in rtatoeba with some words...
I'm working on it. Thanks for the heads up.

**Comment by pcboy** [comment]
Ok. I got your problem. =)
You are using fre as the language parameter. It should be fra! It's ISO-639-2 format.
Tatoeba is kind of annoying with this. I'm still gonna make some checks in that type of situation..
Try fra instead and that should work.

**Comment by kdelwat** [comment]
Well that's embarassing... Thanks for the help!

**Comment by pcboy** [comment]
I added some checks in the rtatoeba library to tell people when they are using an unsupported language format. That should help.  
Thanks!
